
name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Sapper Build
        uses: truewebartisans/actions-sapper@master
        with:
          build_mode: "export"
#           args: "--legacy --entry about"

      - name: Dockerhub login
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} --password-stdin
            
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
            version: latest

      - name: Build dockerfile (with push)
        run: |
            docker buildx build \
            --platform=linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --tag jhonoryza/landing-page:latest
